### ISSUE TITLE
[Suggestion] Return metadata

### ISSUE THREAD

**Issue by rafaell-lycan** [riyadhalnur/node-base64-image#64]
Hi, I'm using this lib for about 4 months now and the only thing I guess could be improved is a new option param that returns the base64 string + some metadata such as `format`, maybe its size (width/height), etc.

The `format` I guess that it's possible to get on the Axios request itself, and the size would be possible to get using something such as [probe-image-size](https://www.npmjs.com/package/probe-image-size).

That's all, cheers.

```js
const response = encode(url, {
    metadata: true, // it could be a better naming fore sure 👍 
})

console.log(response)
/*
 * {
 *     data: <base64>,
 *     format: <jpg, png, etc>,
 *     width: <number>,
 *     height: <number>,
 * }
 */
```

**Comment by riyadhalnur** [comment]
Thank you for opening an issue. While this seems like a good feature to have, I don't it goes with the purpose of the library mostly because the response structure would have to change. I could be convinced to go ahead with this though if there's enough support and/or need from the users of this package.
